/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(base_verilog.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(df6df91afdd9c2223d475326fc62ec4e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dlverilog/base_verilog.h>
// pydoc.h is automatically generated in the build directory
#include <base_verilog_pydoc.h>

void bind_base_verilog(py::module& m)
{

    using base_verilog    = gr::dlverilog::base_verilog;


    py::class_<base_verilog, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<base_verilog>>(m, "base_verilog", D(base_verilog))

        .def(py::init(&base_verilog::make),
           D(base_verilog,make)
        )
        



        ;




}








